version: "3.7"
services:
  db:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
  server:
    build: back-end
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
    ports:
      - "8085:8085"
    depends_on:
      - db
    restart: on-failure
  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/usr/src/app/my-app
       - /usr/src/app/front-end/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - server
    restart: on-failure